### ISSUE TITLE
Balancing Vanilla Armor

### ISSUE THREAD

**Issue by XanderwithanX** [Finnerex/pluggyTesty#6]

**Comment by NoahSimcox** [comment]
[https://docs.google.com/spreadsheets/d/1PMhvSNLe8qNnr9FYN7faVNdlwXQt7JdLUMaa2qJ6kpc/edit#gid=0](url)

**Comment by NoahSimcox** [comment]
[Armors - Sheet1.pdf](https://github.com/Finnerex/pluggyTesty/files/11356814/Armors.-.Sheet1.pdf)
